server:
  port: 8087

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: kafka-holy:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.notificationservice.event

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# mail:
#   host: live.smtp.mailtrap.io
#   port: 587
#   username: api
#   password: 007df15b5fb78264fe8d3855315159d8
#   properties:
#     mail:
#       smtp:
#         auth: true
#         starttls:
#           enable: true