server:
  port: 8084

spring:
  application:
    name: product-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://product-db:5432/product_db
#    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: 123456

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: product-service-group
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "com.example.productservice.event"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      backs: 1
      retries: 3
      properties:
        spring.json.add.type.headers: false
        max.request.size: 20971520

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

jwt:
  secret: j4G$z8LpN9vJ^T3Qb7fE2k!wYcB1uL0zRxH5MvAhDpXsCgKj
  expiration: 3600000
  refreshExpiration: 604800000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
#        defaultZone: http://localhost:8761/eureka

