package com.example.orderservice.enums;

public enum EnumProcessOrder {
    PRE_ORDER,
    PENDING,
    PAYMENT,
    ASSIGN_ORDER_STORE,
    MANAGER_ACCEPT,
    READY_FOR_INVOICE,
    MANAGER_REJECT,
    MANAGER_EXPORT_ORDER,
    CONFIRMED,
    PACKAGED,
    SHIPPING,
    DELIVERED,
    RETURN_REQUESTED,
    RETURN_ACCEPTED,
    RETURN_REJECTED,
    RETURNED,
    FINISHED,
    CANCELLED
}
